apiVersion: v1
kind: Secret
metadata:
  name:  spring-k8s-demo-secret
type: Opaque # the default and most common type of Kubernetes Secret used to store arbitrary, sensitive information.
data:
  SECRET_EXAMPLE_KEY:  BASE64_ENCODED_VALUE
