# Not really used in this project since im only using one deployment (just wanted to try it out)
# But useful for multi-pod deployments
# Using the quick port forwarding command instead
# kubectl port-forward pod/pod-name <local-port>:<container-port>

kind: Service
apiVersion: v1
metadata:
  name: spring-k8s-demo-service # this becomes the host name for http requests (if with microservices)
spec:
  type: ClusterIP # Only accessible within the cluster (the default)
  selector:
    app: spring-k8s-demo # Finds pods that matches this selector
  ports:
    - port:  80 # Port exposed by the service
      targetPort:  8080 # Port exposed by the pod
